// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOnxWKfROimFtjG2jQ_FjWkEviUZkUqf4',
    appId: '1:1044685797284:web:8e862e8579c9097a453331',
    messagingSenderId: '1044685797284',
    projectId: 'dnews-aa04e',
    authDomain: 'dnews-aa04e.firebaseapp.com',
    storageBucket: 'dnews-aa04e.appspot.com',
    measurementId: 'G-QJ70BM6F37',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfqem0QBRJigPK6wxCnigN15lf2FbPrCk',
    appId: '1:1044685797284:android:fec25cc93d93b093453331',
    messagingSenderId: '1044685797284',
    projectId: 'dnews-aa04e',
    storageBucket: 'dnews-aa04e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxOeU7Xt2tpyGOTWF5as22JBBWBPU_x38',
    appId: '1:1044685797284:ios:dd65b137f8cc9a69453331',
    messagingSenderId: '1044685797284',
    projectId: 'dnews-aa04e',
    storageBucket: 'dnews-aa04e.appspot.com',
    iosBundleId: 'com.example.deltanews',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxOeU7Xt2tpyGOTWF5as22JBBWBPU_x38',
    appId: '1:1044685797284:ios:dd65b137f8cc9a69453331',
    messagingSenderId: '1044685797284',
    projectId: 'dnews-aa04e',
    storageBucket: 'dnews-aa04e.appspot.com',
    iosBundleId: 'com.example.deltanews',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOnxWKfROimFtjG2jQ_FjWkEviUZkUqf4',
    appId: '1:1044685797284:web:c9e2d571888d3003453331',
    messagingSenderId: '1044685797284',
    projectId: 'dnews-aa04e',
    authDomain: 'dnews-aa04e.firebaseapp.com',
    storageBucket: 'dnews-aa04e.appspot.com',
    measurementId: 'G-T6V79EZ2Z7',
  );
}
